from django.urls import path

from . import ai_api
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("projects/add/", views.project_create, name="project_create"),
    path("projects/<int:pk>/", views.project_overview, name="project_detail"),
    path("projects/<int:pk>/analytics/", views.project_analytics, name="project_analytics"),
    path("projects/<int:pk>/estimate/", views.project_estimate, name="project_estimate"),
    path("projects/<int:pk>/estimate/vat/", views.estimate_vat_toggle, name="estimate_vat_toggle"),
    path("projects/<int:pk>/estimate/section/add/", views.estimate_section_add, name="estimate_section_add"),
    path("projects/<int:pk>/estimate/section/<int:section_id>/edit/", views.estimate_section_edit, name="estimate_section_edit"),
    path("projects/<int:pk>/estimate/section/<int:section_id>/delete/", views.estimate_section_delete, name="estimate_section_delete"),
    path("projects/<int:pk>/estimate/section/<int:section_id>/item/add/", views.estimate_item_add, name="estimate_item_add"),
    path("projects/<int:pk>/estimate/section/<int:section_id>/item/quick-add/", views.estimate_item_quick_add, name="estimate_item_quick_add"),
    path("projects/<int:pk>/estimate/section/<int:section_id>/item/<int:item_id>/edit/", views.estimate_item_edit, name="estimate_item_edit"),
    path("projects/<int:pk>/estimate/section/<int:section_id>/item/<int:item_id>/inline/", views.estimate_item_inline, name="estimate_item_inline"),
    path("projects/<int:pk>/estimate/section/<int:section_id>/item/<int:item_id>/delete/", views.estimate_item_delete, name="estimate_item_delete"),
    path("projects/<int:pk>/estimate/import/", views.estimate_import, name="estimate_import"),
    path("projects/<int:pk>/estimate/export/", views.estimate_export, name="estimate_export"),
    path("projects/<int:pk>/schedule/", views.project_schedule, name="project_schedule"),
    path(
        "projects/<int:pk>/schedule/item/<int:item_id>/api/",
        views.schedule_item_api,
        name="schedule_item_api",
    ),
    path("projects/<int:pk>/supply/", views.project_supply, name="project_supply"),
    path(
        "projects/<int:pk>/supply/request/create/",
        views.project_supply_request_create,
        name="project_supply_request_create",
    ),
    path(
        "projects/<int:pk>/supply/order/create/",
        views.project_supply_order_create,
        name="project_supply_order_create",
    ),
    path(
        "projects/<int:pk>/supply/request/<int:req_id>/api/",
        views.project_supply_request_api,
        name="project_supply_request_api",
    ),
    path(
        "projects/<int:pk>/supply/order/<int:order_id>/payment/",
        views.project_supply_order_payment,
        name="project_supply_order_payment",
    ),
    path("projects/<int:pk>/finance/", views.project_finance_section, name="project_finance_section"),
    path(
        "projects/<int:pk>/finance/export/",
        views.project_finance_export_journal,
        name="project_finance_export_journal",
    ),
    path(
        "projects/<int:pk>/finance/income/",
        views.project_finance_income_create,
        name="project_finance_income_create",
    ),
    path(
        "projects/<int:pk>/finance/expense/",
        views.project_finance_expense_create,
        name="project_finance_expense_create",
    ),
    path(
        "projects/<int:pk>/finance/operation/<int:op_id>/edit/",
        views.project_finance_operation_edit,
        name="project_finance_operation_edit",
    ),
    path(
        "projects/<int:pk>/finance/operation/<int:op_id>/delete/",
        views.project_finance_operation_soft_delete,
        name="project_finance_operation_soft_delete",
    ),
    path(
        "projects/<int:pk>/finance/pay-supply/<int:order_id>/",
        views.project_finance_pay_supply_order,
        name="project_finance_pay_supply_order",
    ),
    path(
        "projects/<int:pk>/finance/pay-act/<int:act_id>/",
        views.project_finance_pay_work_act,
        name="project_finance_pay_work_act",
    ),
    path(
        "projects/<int:pk>/supply/order/<int:order_id>/submit-payment/",
        views.project_supply_order_submit_payment,
        name="project_supply_order_submit_payment",
    ),
    path(
        "projects/<int:pk>/documents/act/create/",
        views.project_work_act_create,
        name="project_work_act_create",
    ),
    path(
        "projects/<int:pk>/documents/act/<int:act_id>/submit-payment/",
        views.project_work_act_submit_payment,
        name="project_work_act_submit_payment",
    ),
    path("projects/<int:pk>/construction/", views.project_construction, name="project_construction"),
    path(
        "projects/<int:pk>/construction/log/",
        views.project_construction_log,
        name="project_construction_log",
    ),
    path(
        "projects/<int:pk>/construction/journal/export/",
        views.project_construction_journal_export,
        name="project_construction_journal_export",
    ),
    path(
        "projects/<int:pk>/construction/journal/print/",
        views.project_construction_journal_print,
        name="project_construction_journal_print",
    ),
    path("projects/<int:pk>/warehouses/", views.project_warehouses, name="project_warehouses"),
    path("projects/<int:pk>/warehouses/create/", views.project_warehouse_create, name="project_warehouse_create"),
    path("projects/<int:pk>/warehouses/inventory/create/", views.project_inventory_create, name="project_inventory_create"),
    path("projects/<int:pk>/warehouses/inventory/<int:item_id>/update/", views.project_inventory_update, name="project_inventory_update"),
    path("projects/<int:pk>/warehouses/inventory/<int:item_id>/transfer/", views.project_inventory_transfer, name="project_inventory_transfer"),
    path("projects/<int:pk>/documents/", views.project_documents, name="project_documents"),
    path("projects/<int:pk>/ai/", ai_api.project_ai_import, name="project_ai_import"),
    path("projects/<int:pk>/legacy/", views.project_detail, name="project_legacy"),
    path("projects/<int:pk>/edit/", views.project_edit, name="project_edit"),
    path("projects/<int:pk>/delete/", views.project_delete, name="project_delete"),
    # Модуль «Задачи» (страница /tasks/)
    path("tasks/", views.task_list, name="task_list"),
    path("tasks/create/", views.task_create, name="task_create"),
    path("tasks/<int:pk>/edit/", views.task_edit, name="task_edit"),
    path("tasks/<int:pk>/status/", views.task_status, name="task_status"),
    path("tasks/<int:pk>/delete/", views.delete_task, name="task_delete"),
    path("finances/<int:pk>/delete/", views.delete_finance, name="finance_delete"),
    # Модуль «Финансы»: журнал операций
    path("finance/", views.finance_dashboard, name="finance_dashboard"),
    path("finance/income/", views.finance_income, name="finance_income"),
    path("finance/expense/", views.finance_expense, name="finance_expense"),
    path("finance/transfer/", views.finance_transfer, name="finance_transfer"),
    path("finance/operation/<int:pk>/delete/", views.finance_operation_delete, name="finance_operation_delete"),
    # Модуль «Снабжение»
    path("supply/", views.supply_dashboard, name="supply_dashboard"),
    path("supply/request/create/", views.supply_request_create, name="supply_request_create"),
    path("supply/order/create/", views.supply_order_create, name="supply_order_create"),
    path("supply/order/<int:pk>/", views.supply_order_detail, name="supply_order_detail"),
    # Модуль «Склады»
    path("warehouses/", views.warehouse_list, name="warehouses_dashboard"),
    path("warehouses/create/", views.warehouse_create, name="warehouse_create"),
    path("warehouses/<int:pk>/", views.warehouse_detail, name="warehouse_detail"),
    path("warehouses/incoming/", views.warehouses_incoming, name="warehouses_incoming"),
    path("warehouses/stock/incoming/", views.stock_incoming, name="stock_incoming"),
    path("warehouses/stock/writeoff/", views.stock_writeoff, name="stock_writeoff"),
    path("warehouses/stock/transfer/", views.stock_transfer, name="stock_transfer"),
    path("warehouses/materials/create/", views.material_create, name="material_create"),
    path("warehouses/outgoing/", views.warehouses_outgoing, name="warehouses_outgoing"),
    path("warehouses/transfer/", views.warehouses_transfer, name="warehouses_transfer"),
    # Модуль «Отчёты»
    path("reports/", views.reports_index, name="reports_index"),
    path("reports/pnl/", views.reports_pnl, name="reports_pnl"),
    path("reports/cashflow/", views.reports_cashflow, name="reports_cashflow"),
    path("reports/project/<int:id>/", views.reports_project, name="reports_project"),
    path(
        "inventory/<int:pk>/delete/",
        views.delete_inventory_item,
        name="inventory_delete",
    ),
    path("company/settings/", views.company_settings, name="company_settings"),
    # Умный импорт PDF + ИИ (API)
    path("api/upload-pdf/", ai_api.api_upload_pdf, name="api_upload_pdf"),
    path("api/document/<int:doc_id>/", ai_api.api_document_detail, name="api_document_detail"),
    path(
        "api/document/<int:doc_id>/apply/",
        ai_api.api_document_apply,
        name="api_document_apply",
    ),
    # Настройки → Права доступа
    path("settings/access/", views.settings_access, name="settings_access"),
    path("settings/access/add/", views.settings_access_add_user, name="settings_access_add_user"),
    path("settings/access/<int:pk>/edit/", views.settings_access_edit, name="settings_access_edit"),
    path("settings/access/<int:pk>/delete/", views.settings_access_delete, name="settings_access_delete"),
]

