from django.urls import path

from . import superadmin_api, superadmin_views

urlpatterns = [
    path(
        "stop-impersonation/",
        superadmin_views.stop_impersonation,
        name="superadmin_stop_impersonation",
    ),
    path(
        "",
        superadmin_views.superadmin_panel,
        name="superadmin_panel",
    ),
    path(
        "dashboard/",
        superadmin_views.superadmin_dashboard_page,
        name="superadmin_dashboard",
    ),
    path(
        "companies/",
        superadmin_views.superadmin_companies_page,
        name="superadmin_companies",
    ),
    path(
        "users/",
        superadmin_views.superadmin_users_page,
        name="superadmin_users",
    ),
    path(
        "projects/",
        superadmin_views.superadmin_projects_page,
        name="superadmin_projects",
    ),
    path(
        "logs/",
        superadmin_views.superadmin_logs_page,
        name="superadmin_logs",
    ),
    path(
        "tariffs/",
        superadmin_views.superadmin_tariffs_page,
        name="superadmin_tariffs",
    ),
]

api_urlpatterns = [
    path(
        "dashboard/",
        superadmin_api.api_dashboard,
        name="api_superadmin_dashboard",
    ),
    path(
        "companies/",
        superadmin_api.api_companies,
        name="api_superadmin_companies",
    ),
    path(
        "companies/<int:pk>/block/",
        superadmin_api.api_company_block,
        name="api_superadmin_company_block",
    ),
    path(
        "companies/<int:pk>/activate/",
        superadmin_api.api_company_activate,
        name="api_superadmin_company_activate",
    ),
    path(
        "companies/<int:pk>/delete/",
        superadmin_api.api_company_delete,
        name="api_superadmin_company_delete",
    ),
    path(
        "companies/<int:pk>/change-tariff/",
        superadmin_api.api_company_change_tariff,
        name="api_superadmin_company_tariff",
    ),
    path(
        "users/",
        superadmin_api.api_users,
        name="api_superadmin_users",
    ),
    path(
        "users/<int:pk>/reset-password/",
        superadmin_api.api_user_reset_password,
        name="api_superadmin_user_reset_password",
    ),
    path(
        "users/<int:pk>/delete/",
        superadmin_api.api_user_delete,
        name="api_superadmin_user_delete",
    ),
    path(
        "projects/",
        superadmin_api.api_projects,
        name="api_superadmin_projects",
    ),
    path(
        "logs/",
        superadmin_api.api_logs,
        name="api_superadmin_logs",
    ),
    path(
        "tariffs/",
        superadmin_api.api_tariffs,
        name="api_superadmin_tariffs",
    ),
    path(
        "login-as-user/<int:user_id>/",
        superadmin_api.api_login_as_user,
        name="api_superadmin_login_as",
    ),
    path(
        "stop-impersonation/",
        superadmin_api.api_stop_impersonation,
        name="api_superadmin_stop_impersonation",
    ),
]
