# Generated by Django 5.0.6 on 2026-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_warehouse_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='financecategory',
            name='cashflow_group',
            field=models.CharField(blank=True, choices=[('operating', 'Операционная деятельность'), ('investing', 'Инвестиционная'), ('financing', 'Финансовая')], default='', help_text='Для Cash Flow: раздел отчёта (если не задано — Операционная).', max_length=20, verbose_name='Cash Flow группа'),
        ),
        migrations.AddField(
            model_name='financecategory',
            name='pnl_group',
            field=models.CharField(blank=True, choices=[('revenue', 'Выручка'), ('other_income', 'Прочие доходы'), ('variable_expense', 'Переменные расходы'), ('fixed_expense', 'Постоянные расходы'), ('other_expense', 'Прочие расходы'), ('interest', 'Проценты'), ('taxes', 'Налоги'), ('depreciation', 'Амортизация')], default='', help_text='Для P&L: куда относить операции по этой статье (если не задано — применятся дефолты).', max_length=30, verbose_name='P&L группа'),
        ),
    ]
