# Generated by Django 5.0.6 on 2026-02-17 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_options_financecategory_cashflow_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='warehouseoperation',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Для поступления/списания — склад; для перемещения — не используется', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.warehouse'),
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная роль')),
                ('slug', models.CharField(blank=True, help_text='owner / manager / employee для системных ролей', max_length=30, verbose_name='Код (для системных ролей)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.company')),
            ],
            options={
                'verbose_name': 'Роль в компании',
                'verbose_name_plural': 'Роли в компании',
                'ordering': ['is_system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('auto_add_to_new_projects', models.BooleanField(default=False, verbose_name='Автоматически добавлять в новые проекты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='core.company')),
                ('role', models.ForeignKey(blank=True, help_text='Пусто = доступ только через владельца (legacy).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_users', to='core.companyrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь компании',
                'verbose_name_plural': 'Пользователи компании',
                'ordering': ['user__username'],
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(choices=[('manager', 'Руководитель проекта'), ('worker', 'Исполнитель'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20, verbose_name='Роль в проекте')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accesses', to='core.companyuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accesses', to='core.project')),
            ],
            options={
                'verbose_name': 'Доступ к проекту',
                'verbose_name_plural': 'Доступы к проектам',
                'ordering': ['project__name'],
                'unique_together': {('company_user', 'project')},
            },
        ),
    ]
