# Generated by Django 5.0.6 on 2026-03-11 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backfill_company_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_sections', to='core.project')),
            ],
            options={
                'verbose_name': 'Раздел сметы',
                'verbose_name_plural': 'Разделы сметы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('type', models.CharField(choices=[('material', 'Материалы'), ('labor', 'Люди'), ('equipment', 'Механизмы')], default='material', max_length=20, verbose_name='Тип ресурса')),
                ('unit', models.CharField(default='шт', max_length=30, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Количество')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена (себестоимость за ед.)')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена для заказчика за ед.')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16, verbose_name='Себестоимость итого')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16, verbose_name='Итого для заказчика')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.estimatesection')),
            ],
            options={
                'verbose_name': 'Позиция сметы',
                'verbose_name_plural': 'Позиции сметы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
