# Generated by Django 5.0.6 on 2026-03-19 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_estimate_section_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Локация'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('unit', models.CharField(default='шт', max_length=30, verbose_name='Ед. изм.')),
                ('category', models.CharField(choices=[('material', 'Материал'), ('tool', 'Инструмент'), ('equipment', 'Оборудование')], default='material', max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.company')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['category', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('incoming', 'Поступление'), ('outgoing', 'Списание на объект'), ('transfer', 'Перемещение'), ('writeoff', 'Списание')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена за ед.')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.material')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.project', verbose_name='Проект (при списании на объект)')),
                ('warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_out', to='core.warehouse', verbose_name='Склад откуда')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_in', to='core.warehouse', verbose_name='Склад куда')),
            ],
            options={
                'verbose_name': 'Движение',
                'verbose_name_plural': 'Движения',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Количество')),
                ('price_avg', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Средняя цена')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.material')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Остаток (Stock)',
                'verbose_name_plural': 'Остатки (Stock)',
                'unique_together': {('warehouse', 'material')},
            },
        ),
    ]
