# Generated by Django 5.0.6 on 2026-03-19 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_warehouse_material_stock_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
        migrations.CreateModel(
            name='WarehouseInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('inventory_number', models.CharField(blank=True, max_length=100, verbose_name='Инвентарный номер')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('in_use', 'В работе'), ('broken', 'Сломан'), ('written_off', 'Списан')], default='free', max_length=20, verbose_name='Статус')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Стоимость (₽)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.FileField(blank=True, null=True, upload_to='inventory/', verbose_name='Фото')),
                ('available_from', models.DateField(blank=True, help_text='Дата освобождения при статусе «В работе»', null=True, verbose_name='Будет свободен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory_items', to='core.company')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory_items', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентарь',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.warehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.warehouse')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transfers', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.warehouseinventoryitem')),
            ],
            options={
                'verbose_name': 'Перемещение инвентаря',
                'verbose_name_plural': 'Перемещения инвентаря',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан инвентарь'), ('moved', 'Перемещён'), ('updated', 'Изменён'), ('status_changed', 'Изменён статус')], max_length=20, verbose_name='Действие')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.warehouseinventoryitem')),
            ],
            options={
                'verbose_name': 'Запись истории инвентаря',
                'verbose_name_plural': 'История инвентаря',
                'ordering': ['-created_at'],
            },
        ),
    ]
