# Generated by Django 5.0.6 on 2026-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_inventory_kanban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название'),
        ),
    ]
