# Generated by Django 5.0.6 on 2026-04-06 07:22

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def backfill_markup_percent(apps, schema_editor):
    EstimateItem = apps.get_model("core", "EstimateItem")
    for row in EstimateItem.objects.all():
        cp = row.cost_price or Decimal("0")
        sp = row.sell_price or Decimal("0")
        qty = row.quantity or Decimal("0")
        if cp > 0:
            markup = ((sp / cp) - Decimal("1")) * Decimal("100")
        else:
            markup = Decimal("0")
        new_sell = (cp * (Decimal("1") + markup / Decimal("100"))).quantize(
            Decimal("0.01"), rounding=ROUND_HALF_UP
        )
        total_cost = (cp * qty).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        total_price = (new_sell * qty).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        EstimateItem.objects.filter(pk=row.pk).update(
            markup_percent=markup,
            sell_price=new_sell,
            total_cost=total_cost,
            total_price=total_price,
        )


def backfill_markup_percent_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_estimateitem_name_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimateitem",
            name="markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена заказчика за ед. = цена × (1 + наценка / 100)",
                max_digits=8,
                verbose_name="Наценка, %",
            ),
        ),
        migrations.AlterField(
            model_name="estimateitem",
            name="sell_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=14,
                verbose_name="Цена для заказчика за ед.",
            ),
        ),
        migrations.AlterField(
            model_name="estimateitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("material", "Материалы"),
                    ("labor", "Работы"),
                    ("equipment", "Механизмы"),
                    ("delivery", "Доставка"),
                ],
                default="material",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.RunPython(backfill_markup_percent, backfill_markup_percent_reverse),
    ]
