# Generated by Django 5.0.6 on 2026-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_estimateitem_markup_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimate_vat_enabled',
            field=models.BooleanField(default=False, verbose_name='Учитывать НДС 16% в итогах для заказчика'),
        ),
    ]
