# Generated by Django 5.0.6 on 2026-04-06 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_project_estimate_vat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('plan', 'План'), ('in_progress', 'В работе'), ('done', 'Завершено')], default='plan', max_length=20, verbose_name='Статус')),
                ('progress_percent', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Прогресс, %')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_phases', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_phases', to='core.schedulephase', verbose_name='Предыдущий этап (завершение до старта этого)')),
                ('estimate_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_phases', to='core.estimatesection', verbose_name='Раздел сметы')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_phases', to='core.project')),
            ],
            options={
                'verbose_name': 'Этап графика работ',
                'verbose_name_plural': 'Этапы графика работ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
