# Generated by Django 5.0.6 on 2026-04-06 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_schedulephase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSchedulePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %')),
                ('status', models.CharField(choices=[('planned', 'План'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='planned', max_length=20, verbose_name='Статус')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('estimate_cost_cache', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Стоимость по смете (кэш)')),
                ('work_volume_cache', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Объём работ по смете (кэш)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_phases_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('estimate_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_phases', to='core.estimatesection', verbose_name='Раздел сметы')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='core.projectschedulephase', verbose_name='Предыдущий этап (зависимость)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_phases', to='core.project')),
            ],
            options={
                'verbose_name': 'Этап графика работ',
                'verbose_name_plural': 'Этапы графика работ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='SchedulePhase',
        ),
    ]
