# Generated by Django 5.0.6 on 2026-04-08 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_supply_order_payments(apps, schema_editor):
    SupplyOrder = apps.get_model("core", "SupplyOrder")
    FinanceOperation = apps.get_model("core", "FinanceOperation")
    for o in SupplyOrder.objects.all():
        fo_id = getattr(o, "finance_operation_id", None)
        if fo_id:
            FinanceOperation.objects.filter(pk=fo_id).update(
                supply_order_id=o.id,
                basis="supply_order",
                journal_status="paid",
            )
            o.paid_amount = o.total_amount or 0
            o.payment_status = "paid"
            o.save(update_fields=["paid_amount", "payment_status"])
        elif o.payment_status == "unpaid":
            o.payment_status = "awaiting_payment"
            o.save(update_fields=["payment_status"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_supply_enhancement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financeoperation',
            name='basis',
            field=models.CharField(choices=[('manual', 'Вручную'), ('supply_order', 'Заказ поставщику'), ('work_act', 'Акт работ'), ('estimate', 'Смета / план')], default='manual', max_length=20, verbose_name='Основание'),
        ),
        migrations.AddField(
            model_name='financeoperation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='financeoperation',
            name='journal_status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('partial', 'Частично'), ('planned', 'План')], default='paid', help_text='Оплачено/частично/план — для учёта кассовых и обязательств.', max_length=10, verbose_name='Статус в журнале'),
        ),
        migrations.AddField(
            model_name='financeoperation',
            name='supply_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_operations', to='core.supplyorder', verbose_name='Заказ снабжения'),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Оплачено по заказу'),
        ),
        migrations.RunPython(migrate_supply_order_payments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supplyorder',
            name='payment_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('awaiting_payment', 'Ожидает оплаты'), ('partial', 'Частично оплачено'), ('paid', 'Оплачено')], default='draft', max_length=20, verbose_name='Оплата'),
        ),
        migrations.CreateModel(
            name='WorkAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(max_length=255, verbose_name='Подрядчик')),
                ('work_type', models.CharField(blank=True, max_length=500, verbose_name='Вид работ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма акта')),
                ('act_date', models.DateField(verbose_name='Дата акта')),
                ('payment_status', models.CharField(choices=[('draft', 'Черновик'), ('awaiting_payment', 'Ожидает оплаты'), ('partial', 'Частично оплачено'), ('paid', 'Оплачено')], default='draft', max_length=20, verbose_name='Статус оплаты')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Оплачено')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_acts', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_acts_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_acts', to='core.project')),
            ],
            options={
                'verbose_name': 'Акт работ',
                'verbose_name_plural': 'Акты работ',
                'ordering': ['-act_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='financeoperation',
            name='work_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_operations', to='core.workact', verbose_name='Акт работ'),
        ),
    ]
