# Generated by Django 5.0.6 on 2026-04-08 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_project_finance_work_acts_and_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='construction_actual_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Сумма объёмов из журнала отчётов прораба.', max_digits=14, verbose_name='Стройка: выполнено (факт)'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='construction_exec_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('overdue', 'Просрочено')], default='not_started', max_length=20, verbose_name='Стройка: статус'),
        ),
        migrations.CreateModel(
            name='ConstructionWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Дата выполнения')),
                ('volume', models.DecimalField(decimal_places=4, help_text='Прибавляется к факту позиции.', max_digits=14, verbose_name='Объём (за отчёт)')),
                ('comment', models.CharField(blank=True, max_length=2000, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_work_logs', to=settings.AUTH_USER_MODEL)),
                ('estimate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_logs', to='core.estimateitem', verbose_name='Позиция сметы')),
            ],
            options={
                'verbose_name': 'Запись журнала стройки',
                'verbose_name_plural': 'Журнал стройки',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionWorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='construction/%Y/%m/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.constructionworklog', verbose_name='Запись журнала')),
            ],
            options={
                'verbose_name': 'Фото (стройка)',
                'verbose_name_plural': 'Фото (стройка)',
            },
        ),
    ]
