# Generated by Django 5.0.6 on 2026-04-16 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_construction_work_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaccess',
            name='role_in_project',
            field=models.CharField(choices=[('manager', 'Руководитель проекта'), ('worker', 'Исполнитель (прораб)'), ('viewer', 'Наблюдатель (только просмотр)')], default='viewer', max_length=20, verbose_name='Роль в проекте'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('delivered', 'Поставлен'), ('closed', 'Закрыт')], default='new', max_length=20, verbose_name='Статус поставки'),
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_type', models.CharField(choices=[('residential', 'Жилой дом'), ('commercial', 'Коммерческий объект'), ('renovation', 'Ремонт')], default='residential', max_length=20, verbose_name='Тип объекта')),
                ('parsed_text', models.TextField(blank=True, null=True, verbose_name='Извлечённый текст')),
                ('ai_result', models.JSONField(blank=True, null=True, verbose_name='Результат ИИ')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processing', 'Обработка'), ('done', 'Готово'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='core.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Загруженный документ (ИИ)',
                'verbose_name_plural': 'Загруженные документы (ИИ)',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
