# Generated by Django 5.0.6 on 2026-04-21 08:22

from django.db import migrations, models


PERMISSION_ROWS = [
    ("view_projects", "Проекты: просмотр"),
    ("edit_projects", "Проекты: редактирование"),
    ("view_estimates", "Смета: просмотр"),
    ("edit_estimates", "Смета: редактирование"),
    ("view_schedule", "График работ: просмотр"),
    ("edit_schedule", "График работ: редактирование"),
    ("view_supply", "Снабжение: просмотр"),
    ("edit_supply", "Снабжение: редактирование"),
    ("view_warehouse", "Склады: просмотр"),
    ("edit_warehouse", "Склады: редактирование"),
    ("view_finance", "Финансы: просмотр"),
    ("edit_finance", "Финансы: редактирование"),
    ("view_reports", "Отчёты: просмотр"),
    ("manage_users", "Настройки и пользователи"),
    ("view_tasks", "Задачи: просмотр"),
    ("edit_tasks", "Задачи: редактирование"),
    ("view_construction", "Стройка: просмотр"),
    ("edit_construction", "Стройка: редактирование"),
    ("view_ai", "ИИ-импорт: просмотр"),
    ("edit_ai", "ИИ-импорт: использование"),
]


def seed_rbac(apps, schema_editor):
    Permission = apps.get_model("core", "Permission")
    Company = apps.get_model("core", "Company")
    CompanyRole = apps.get_model("core", "CompanyRole")

    for code, name in PERMISSION_ROWS:
        Permission.objects.get_or_create(code=code, defaults={"name": name})

    perm_by_code = {p.code: p for p in Permission.objects.all()}
    all_codes = list(perm_by_code.keys())
    employee_codes = [
        c
        for c in all_codes
        if c not in ("view_finance", "edit_finance", "view_reports", "manage_users")
    ]

    slug_to_codes = {
        "owner": all_codes,
        "manager": all_codes,
        "employee": employee_codes,
        "pto": [
            "view_projects",
            "edit_projects",
            "view_estimates",
            "edit_estimates",
            "view_schedule",
            "edit_schedule",
        ],
        "supply": [
            "view_projects",
            "view_supply",
            "edit_supply",
            "view_warehouse",
            "edit_warehouse",
        ],
        "accountant": ["view_finance", "edit_finance", "view_reports"],
    }

    extras = [
        ("pto", "ПТО", "Проекты, смета, график работ"),
        ("supply", "Снабженец", "Снабжение и склады"),
        ("accountant", "Бухгалтер", "Финансы и отчёты"),
    ]
    for company in Company.objects.all():
        for slug, name, desc in extras:
            CompanyRole.objects.get_or_create(
                company=company,
                slug=slug,
                defaults={
                    "name": name,
                    "description": desc,
                    "is_system": True,
                },
            )

    CompanyRole.objects.filter(slug="manager", name__icontains="только просмотр").update(
        name="Руководитель",
        description="Полный доступ ко всем модулям",
    )

    for role in CompanyRole.objects.all():
        slug = (role.slug or "").strip()
        codes = slug_to_codes.get(slug)
        if not codes:
            codes = employee_codes
        role.permissions.set(
            [perm_by_code[c] for c in codes if c in perm_by_code]
        )


def seed_rbac_reverse(apps, schema_editor):
    CompanyRole = apps.get_model("core", "CompanyRole")
    for role in CompanyRole.objects.all():
        role.permissions.clear()
    Permission = apps.get_model("core", "Permission")
    Permission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_uploaded_document_ai_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='slug',
            field=models.CharField(blank=True, help_text='owner / manager / employee / pto / supply / accountant', max_length=30, verbose_name='Код (для системных ролей)'),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='company_roles', to='core.permission', verbose_name='Права'),
        ),
        migrations.RunPython(seed_rbac, seed_rbac_reverse),
    ]
