# Generated by Django 5.0.6 on 2026-04-27 07:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_tariffs_and_profiles(
    apps,
    schema_editor,
):
    Tariff = apps.get_model(
        "core",
        "Tariff",
    )
    User = apps.get_model(
        "auth",
        "User",
    )
    UserProfile = apps.get_model(
        "core",
        "UserProfile",
    )
    Company = apps.get_model(
        "core",
        "Company",
    )
    free, _ = Tariff.objects.get_or_create(
        name="Free",
        defaults={
            "max_projects": 10,
            "max_users": 5,
            "trial_days": 14,
            "is_public": True,
        },
    )
    Tariff.objects.get_or_create(
        name="Pro",
        defaults={
            "max_projects": 100,
            "max_users": 50,
            "trial_days": 14,
            "is_public": True,
        },
    )
    Tariff.objects.get_or_create(
        name="Enterprise",
        defaults={
            "max_projects": 0,
            "max_users": 0,
            "trial_days": 30,
            "is_public": True,
        },
    )
    for u in User.objects.iterator():
        UserProfile.objects.get_or_create(
            user_id=u.pk,
            defaults={
                "is_super_admin": False,
            },
        )
    Company.objects.filter(
        tariff__isnull=True,
    ).update(
        tariff_id=free.pk,
    )


def noop_reverse(
    apps,
    schema_editor,
):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rbac_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('max_projects', models.PositiveIntegerField(default=0, help_text='0 — без ограничения', verbose_name='Макс. проектов')),
                ('max_users', models.PositiveIntegerField(default=0, help_text='0 — без ограничения', verbose_name='Макс. пользователей в компании')),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='Для автопроставления trial', verbose_name='Дней пробного периода')),
                ('is_public', models.BooleanField(default=True, verbose_name='Доступен для назначения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='account_status',
            field=models.CharField(choices=[('active', 'Активен'), ('trial', 'Пробный период'), ('expired', 'Подписка истекла'), ('blocked', 'Заблокирован')], default='active', max_length=20, verbose_name='Статус аккаунта'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создана'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если выключено — вход для компании заблокирован (кроме супер-админа).', verbose_name='Доступ к платформе'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(default='Trial', max_length=100, verbose_name='Тарифный план (legacy)'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('entity', models.CharField(max_length=100, verbose_name='Сущность')),
                ('entity_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID сущности')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись активности',
                'verbose_name_plural': 'Журнал активности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.tariff', verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='Супер-администратор платформы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saas_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя (SaaS)',
                'verbose_name_plural': 'Профили пользователей (SaaS)',
            },
        ),
        migrations.RunPython(
            seed_tariffs_and_profiles,
            noop_reverse,
        ),
    ]
