# Generated by Django 5.0.6 on 2026-04-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_saas_superadmin_tariffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Пусто = доступ только через владельца (legacy). При удалении роли поле обнуляется; при удалении компании роли и участники удаляются каскадно.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_users', to='core.companyrole'),
        ),
    ]
