# Generated by Django 5.0.6 on 2026-05-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_estimateitem_name_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='pdf_norm_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Импорт PDF: шифр нормы'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='pdf_pos_no',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Импорт PDF: № п/п'),
        ),
    ]
