# Generated by Django 5.0.6 on 2026-05-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_estimateitem_pdf_import_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaccess',
            name='role_in_project',
            field=models.CharField(choices=[('manager', 'Руководитель проекта'), ('worker', 'Исполнитель'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20, verbose_name='Роль в проекте'),
        ),
    ]
