# Generated by Django 5.0.6 on 2026-05-15 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fix_legacy_broken_status(apps, schema_editor):
    WarehouseInventoryItem = apps.get_model("core", "WarehouseInventoryItem")
    WarehouseInventoryItem.objects.filter(status="broken").update(status="repair")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_projectaccess_role_in_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fix_legacy_broken_status, migrations.RunPython.noop),
        migrations.CreateModel(
            name='InventoryNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=16, verbose_name='Ключ (INS, TOOL, EQP, EL…)')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Последнее значение')),
            ],
            options={
                'verbose_name': 'Счётчик инвентарных номеров',
                'verbose_name_plural': 'Счётчики инвентарных номеров',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='inventory_prefix',
            field=models.CharField(blank=True, default='', help_text='Напр. BKC для формата BKC-INS-000001. Если пусто — из названия компании.', max_length=8, verbose_name='Префикс инвентарных номеров'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Детали'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Кому выдано'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='category',
            field=models.CharField(choices=[('tool', 'Инструмент'), ('equipment', 'Оборудование'), ('electric', 'Электрика'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_items', to='core.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/qr/', verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='return_due_at',
            field=models.DateField(blank=True, null=True, verbose_name='Срок возврата'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='warehouseinventoryitem',
            name='warranty_until',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия до'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('created', 'Создан инвентарь'), ('moved', 'Перемещён'), ('updated', 'Изменён'), ('status_changed', 'Изменён статус'), ('issued', 'Выдан сотруднику'), ('returned', 'Возврат'), ('repair', 'На ремонте'), ('writeoff', 'Списан'), ('lost', 'Потерян')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='warehouseinventoryitem',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('in_use', 'В работе'), ('issued', 'Выдан'), ('repair', 'На ремонте'), ('written_off', 'Списан'), ('lost', 'Потерян')], default='free', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='warehouseinventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_number', ''), _negated=True), fields=('company', 'inventory_number'), name='uniq_inventory_number_per_company_when_set'),
        ),
        migrations.AddField(
            model_name='inventorynumbersequence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sequences', to='core.company'),
        ),
        migrations.AddConstraint(
            model_name='inventorynumbersequence',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='uniq_inventory_seq_company_key'),
        ),
    ]
