# Generated by Django 5.0.6 on 2026-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_materials_project_enhance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('incoming', 'Поступление'), ('outgoing', 'Расход на объект'), ('transfer', 'Перемещение'), ('writeoff', 'Списание')], max_length=20, verbose_name='Тип операции'),
        ),
    ]
