# Generated by Django 5.0.6 on 2026-05-17 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_material_columns_if_missing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название / госномер')),
                ('fuel_consumption_liters_per_hour', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Расход, л/час')),
                ('tank_capacity_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Объём бака, л')),
                ('engine_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Моточасы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_equipment', to='core.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_equipment', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Техника (ГСМ)',
                'verbose_name_plural': 'Техника (ГСМ)',
                'ordering': ['project_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Стабильный ключ, напр. ai92, diesel, custom_uuid', max_length=32, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('unit', models.CharField(default='л', max_length=30, verbose_name='Ед. изм.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types', to='core.company')),
            ],
            options={
                'verbose_name': 'Вид топлива (ГСМ)',
                'verbose_name_plural': 'Виды топлива (ГСМ)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('incoming', 'Приход'), ('issue', 'Выдача'), ('writeoff', 'Списание')], max_length=20, verbose_name='Операция')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена за ед.')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Поставщик')),
                ('document_number', models.CharField(blank=True, max_length=120, verbose_name='Номер документа')),
                ('recipient_type', models.CharField(blank=True, choices=[('equipment', 'Техника'), ('employee', 'Сотрудник'), ('project', 'Объект'), ('contractor', 'Подрядчик')], max_length=20, verbose_name='Кому (тип)')),
                ('issued_to_name', models.CharField(blank=True, max_length=255, verbose_name='Кому выдано (текст)')),
                ('equipment_name', models.CharField(blank=True, max_length=255, verbose_name='Техника (текст)')),
                ('contractor_name', models.CharField(blank=True, max_length=255, verbose_name='Подрядчик')),
                ('writeoff_reason', models.CharField(blank=True, choices=[('machinery', 'Работа техники'), ('transport', 'Транспорт'), ('generator', 'Генератор'), ('loss', 'Потери')], max_length=20, verbose_name='Причина списания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_issues', to='core.fuelequipment', verbose_name='Техника (справочник)')),
                ('target_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='core.project', verbose_name='Объект')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='core.warehouse', verbose_name='Склад')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.fueltype')),
            ],
            options={
                'verbose_name': 'Операция ГСМ',
                'verbose_name_plural': 'Операции ГСМ',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Количество')),
                ('price_avg', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Средняя цена за ед.')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stocks', to='core.warehouse')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.fueltype')),
            ],
            options={
                'verbose_name': 'Остаток ГСМ',
                'verbose_name_plural': 'Остатки ГСМ',
            },
        ),
        migrations.AddField(
            model_name='fuelequipment',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='core.fueltype', verbose_name='Тип топлива'),
        ),
        migrations.AddConstraint(
            model_name='fueltype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_fueltype_company_code'),
        ),
        migrations.AddConstraint(
            model_name='fuelstock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'fuel_type'), name='uniq_fuelstock_wh_type'),
        ),
    ]
