# Generated by Django 5.0.6 — справочник техники + перенос с FuelEquipment

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_fuel_equipment_rows(apps, schema_editor):
    FuelEquipment = apps.get_model("core", "FuelEquipment")
    Equipment = apps.get_model("core", "Equipment")
    FuelTransaction = apps.get_model("core", "FuelTransaction")
    mapping = {}
    for fe in FuelEquipment.objects.all():
        eq = Equipment(
            company_id=fe.company_id,
            project_id=fe.project_id,
            name=(fe.name or "Без названия")[:255],
            fuel_type_id=fe.fuel_type_id,
            consumption_norm_liters=fe.fuel_consumption_liters_per_hour,
            consumption_norm_mode="per_hour",
            tank_capacity_liters=fe.tank_capacity_liters,
            engine_hours=fe.engine_hours,
            status="free",
        )
        eq.save()
        mapping[fe.id] = eq.id
    for tx in FuelTransaction.objects.exclude(equipment_id__isnull=True):
        nid = mapping.get(tx.equipment_id)
        if nid:
            tx.equipment_catalog_id = nid
            tx.save(update_fields=["equipment_catalog_id"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_fuel_gsm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fueltransaction",
            name="driver_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Водитель / ответственный",
            ),
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Наименование техники"),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Тип техники"
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(blank=True, max_length=32, verbose_name="Госномер"),
                ),
                (
                    "inventory_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Инвентарный номер"
                    ),
                ),
                ("vin", models.CharField(blank=True, max_length=32, verbose_name="VIN")),
                (
                    "make_model",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Марка / модель"
                    ),
                ),
                (
                    "year_manufactured",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "consumption_norm_liters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Норма расхода (литры)",
                    ),
                ),
                (
                    "consumption_norm_mode",
                    models.CharField(
                        choices=[
                            ("per_hour", "л / час"),
                            ("per_100km", "л / 100 км"),
                        ],
                        default="per_hour",
                        max_length=20,
                        verbose_name="Норма: режим",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_work", "В работе"),
                            ("on_site", "На объекте"),
                            ("repair", "На ремонте"),
                            ("free", "Свободна"),
                            ("written_off", "Списана"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="equipment/%Y/%m/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "odometer_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Пробег, км",
                    ),
                ),
                (
                    "engine_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Моточасы",
                    ),
                ),
                (
                    "tank_capacity_liters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Объём бака, л",
                    ),
                ),
                (
                    "qr_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Токен QR",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="based_equipment",
                        to="core.warehouse",
                        verbose_name="Склад базирования",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_units",
                        to="core.company",
                    ),
                ),
                (
                    "fuel_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_preferred_fuel",
                        to="core.fueltype",
                        verbose_name="Тип топлива",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_units",
                        to="core.project",
                        verbose_name="Объект / проект",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_responsible",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
            ],
            options={
                "verbose_name": "Техника (справочник)",
                "verbose_name_plural": "Справочник техники",
                "ordering": ["company_id", "name"],
            },
        ),
        migrations.AddField(
            model_name="fueltransaction",
            name="equipment_catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.equipment",
                verbose_name="Техника (справочник) новая",
            ),
        ),
        migrations.RunPython(migrate_fuel_equipment_rows, noop_reverse),
        migrations.RemoveField(
            model_name="fueltransaction",
            name="equipment",
        ),
        migrations.RenameField(
            model_name="fueltransaction",
            old_name="equipment_catalog",
            new_name="equipment",
        ),
        migrations.AlterField(
            model_name="fueltransaction",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fuel_issue_transactions",
                to="core.equipment",
                verbose_name="Техника (справочник)",
            ),
        ),
        migrations.DeleteModel(
            name="FuelEquipment",
        ),
        migrations.CreateModel(
            name="EquipmentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Событие")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.equipment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "История изменений техники",
                "verbose_name_plural": "История изменений техники",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Название"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="equipment/docs/%Y/%m/", verbose_name="Файл"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ техники",
                "verbose_name_plural": "Документы техники",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentFuelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="core.equipment",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_fuel_log",
                        to="core.fueltransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заправка техники (ГСМ)",
                "verbose_name_plural": "Заправки техники (ГСМ)",
                "ordering": ["-created_at"],
            },
        ),
    ]
