# Generated by Django 5.0.6 on 2026-05-17 14:02

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_equipment_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.projectdocumentfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='core.project')),
            ],
            options={
                'verbose_name': 'Папка документов проекта',
                'verbose_name_plural': 'Папки документов проекта',
                'ordering': ['project_id', 'parent_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectConstructionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.construction_project_upload_to, verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file_kind', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('spreadsheet', 'Excel'), ('image', 'Фото'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип файла')),
                ('category', models.CharField(choices=[('general', 'Общее'), ('aosr', 'АОСР'), ('exec_scheme', 'Исполнительные схемы'), ('contract', 'Договоры'), ('drawing', 'Чертежи')], default='general', max_length=20, verbose_name='Категория')),
                ('workflow_status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('signed', 'Подписан'), ('archive', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('act_number', models.CharField(blank=True, max_length=120, verbose_name='Номер акта')),
                ('act_date', models.DateField(blank=True, null=True, verbose_name='Дата акта')),
                ('work_section', models.CharField(blank=True, max_length=255, verbose_name='Раздел работ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_files', to='core.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_files_uploaded', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='core.projectdocumentfolder')),
            ],
            options={
                'verbose_name': 'Документ строительства',
                'verbose_name_plural': 'Документы строительства',
                'ordering': ['-updated_at', '-pk'],
            },
        ),
    ]
