# Generated by Django 5.0.6 on 2026-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('incoming', 'Поступление'), ('outgoing', 'Расход на объект'), ('transfer', 'Перемещение'), ('writeoff', 'Списание'), ('manual_edit', 'Правка карточки'), ('stock_remove', 'Удаление позиции')], max_length=20, verbose_name='Тип операции'),
        ),
    ]
