# Generated by Django 5.0.6 on 2026-05-29 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_schedule_status_extended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон')),
                ('brigade', models.CharField(blank=True, default='', max_length=128, verbose_name='Бригада')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='core.project')),
            ],
            options={
                'verbose_name': 'Табель',
                'verbose_name_plural': 'Табели',
                'ordering': ['-year', '-month', 'id'],
                'unique_together': {('project', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(blank=True, choices=[('present', 'Явка'), ('off', 'Выходной'), ('vacation', 'Отпуск'), ('absent', 'Неявка'), ('half', 'Полдня')], default='', max_length=16, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_edits', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='core.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='core.project')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.timesheet')),
            ],
            options={
                'verbose_name': 'Запись табеля',
                'verbose_name_plural': 'Записи табеля',
                'ordering': ['date', 'employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('old_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(blank=True, default='', max_length=16)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_change_logs', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_logs', to='core.employee')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='core.timesheetentry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_logs', to='core.project')),
            ],
            options={
                'verbose_name': 'Изменение табеля',
                'verbose_name_plural': 'Журнал табеля',
                'ordering': ['-edited_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='На объекте')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='core.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_employees', to='core.project')),
            ],
            options={
                'verbose_name': 'Сотрудник на объекте',
                'verbose_name_plural': 'Сотрудники на объекте',
                'ordering': ['employee__full_name', 'id'],
                'unique_together': {('project', 'employee')},
            },
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['project', 'date'], name='core_timesh_project_cd962d_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['employee', 'date'], name='core_timesh_employe_3e2769_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheetentry',
            unique_together={('timesheet', 'employee', 'date')},
        ),
    ]
