# Generated by Django 5.0.6 on 2026-06-01 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_timesheet_rbac_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffEstimateSupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, verbose_name='№ заявки')),
                ('material_name', models.CharField(max_length=255, verbose_name='Наименование материала')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Количество')),
                ('price_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Плановая цена')),
                ('total_plan', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Плановая сумма')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Требуется к дате')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочно')], default='medium', max_length=16, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('pending', 'Ожидает закупки'), ('approval', 'На согласовании'), ('approved', 'Одобрена'), ('in_progress', 'В закупке'), ('partial', 'Частично закуплена'), ('purchased', 'Закуплена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('quantity_purchased', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Фактически закуплено')),
                ('total_purchased', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма закупки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse_received', models.BooleanField(default=False, verbose_name='Принято на склад')),
                ('warehouse_received_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='off_estimate_supply_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_estimate_supply_requests', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='off_estimate_supply_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='off_estimate_supply_requests', to='core.material', verbose_name='Материал на складе')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_estimate_supply_requests', to='core.project')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='off_estimate_supply_requests', to='core.warehouse', verbose_name='Склад поступления')),
            ],
            options={
                'verbose_name': 'Заявка вне сметы',
                'verbose_name_plural': 'Заявки вне сметы',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='offestimatesupplyrequest',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_off_estimate_supply_number_per_company'),
        ),
    ]
