# Generated by Django 5.0.6 on 2026-06-01 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_off_estimate_item_note_no_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offestimatesupplyrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='offestimatesupplyrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='off_estimate_supply_approved', to=settings.AUTH_USER_MODEL, verbose_name='Согласовал'),
        ),
        migrations.AddField(
            model_name='offestimatesupplyrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='off_estimate_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_order', to='core.offestimatesupplyrequest', verbose_name='Заявка вне сметы'),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='procurement_status',
            field=models.CharField(choices=[('pending', 'Ожидает закупки'), ('in_progress', 'В закупке'), ('partial', 'Частично закуплена'), ('purchased', 'Закуплена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус закупки'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='line_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='line_unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ед. изм.'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_order_items', to='core.material', verbose_name='Материал на складе'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='off_estimate_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='core.offestimatesupplyrequestitem', verbose_name='Позиция вне сметы'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='quantity_purchased',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Закуплено'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_order_items', to='core.warehouse', verbose_name='Склад поступления'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='warehouse_received',
            field=models.BooleanField(default=False, verbose_name='Принято на склад'),
        ),
        migrations.AddField(
            model_name='supplyorderitem',
            name='warehouse_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='Согласовал'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='supply_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_requests', to='core.supplyorder', verbose_name='Заказ снабжения'),
        ),
        migrations.AlterField(
            model_name='offestimatesupplyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает закупки'), ('approval', 'На согласовании'), ('approved', 'Одобрена'), ('in_progress', 'В закупке'), ('partial', 'Частично закуплена'), ('purchased', 'Закуплена'), ('cancelled', 'Отменена')], default='approval', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplyorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Требуется'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На согласовании'), ('approved', 'Одобрена'), ('pending', 'Ожидает закупки'), ('in_progress', 'В закупке'), ('partial', 'Частично закуплено'), ('purchased', 'Закуплено'), ('cancelled', 'Отменена')], default='approval', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SupplyWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('approved', 'Согласование'), ('rejected', 'Отказ'), ('procurement_started', 'Передача в закупку'), ('partial_purchase', 'Частичная закупка'), ('full_purchase', 'Полная закупка'), ('warehouse_transfer', 'Передача на склад'), ('cancelled', 'Отмена')], max_length=32, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_workflow_logs', to='core.company')),
                ('off_estimate_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='core.offestimatesupplyrequest')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_workflow_logs', to='core.project')),
                ('supply_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='core.supplyorder')),
                ('supply_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='core.supplyrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_workflow_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие снабжения',
                'verbose_name_plural': 'Журнал снабжения',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
