# Generated by Django 5.0.6 on 2026-06-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_expense_journal_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensejournalentry",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kaspi", "Каспи"),
                    ("cash", "Наличные"),
                    ("halyk", "Halyk"),
                    ("accountable", "Подотчет"),
                ],
                default="",
                max_length=32,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
