# Generated by Django 5.0.6 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_remove_forte_bereke_payment_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensejournalentry",
            name="checked",
            field=models.BooleanField(default=False, verbose_name="Чек"),
        ),
        migrations.AddField(
            model_name="expensejournalentry",
            name="receipt_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="expense_journal/receipts/%Y/%m/",
                verbose_name="PDF чека",
            ),
        ),
    ]
