# Generated by Django 5.0.6 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_expense_journal_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplyorderdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("kp", "Коммерческое предложение"),
                    ("invoice", "Счёт на оплату"),
                    ("payment_proof", "Платёжное поручение"),
                    ("poa", "Доверенность"),
                ],
                max_length=16,
                verbose_name="Тип",
            ),
        ),
    ]
